### PR TITLE
LPS-55018

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by zxdgoal** [comment]
Hey Byran

One quick question: if I changed bbcode-parser.js, should I always have the same change for converter.js if there is ?

If yes, it seems that I lost some changes here https://github.com/hhuijser/liferay-portal/commit/c20c08dd20741385c05a1d295246ca6188ac1a83#diff-74eb19d2d0cf6b8f49177aab02b1e8e6R301

and here https://github.com/hhuijser/liferay-portal/commit/c20c08dd20741385c05a1d295246ca6188ac1a83#diff-74eb19d2d0cf6b8f49177aab02b1e8e6R367

**Comment by blzaugg** [comment]
You'll need to ask @ipeychev about that.

Since I'm unable to get `master` running to test this. I'm just going forward this to him, as I'd be sending it to him anyway.

**Comment by blzaugg** [comment]
Forwarded to: https://github.com/ipeychev/liferay-portal/pull/563

**Comment by ipeychev** [comment]
Yes, all the changes should be done in converter (or in some of the other files of the parser). The "bbcode-parser.js" files is actually automatically generated by a task in portal-web/build.xml. Look for "build-ckeditor-plugins-bbcode" target.

This is being done for performance reasons, otherwise we would have to load three or more files separately. In this case we have only one. The files are being minimized by our minimizer in production so there is no need to do that.

So, if you have made changes only to "bbcode-parser.js" file, please go and apply them to the other files in this folder, then run "ant build-ckeditor-plugins-bbcode" from portal-web directory in order to build the combined file.

Thanks,

@zxdgoal 
@blzaugg

**Comment by zxdgoal** [comment]
will resent.

**Pull request closed without merging**
