### PR TITLE
[Technical Support] LPS-59538

### PR DESCRIPTION
**Pull request by zsagia**
Hi Byran,

Please review Peter's solution. I think we need to change the hard coded logic because in some cases the formatter string will be incorrect.

For example: Locales:
"de": "21.08.2015" will be changed to "21/08/2015"
"hu": "2015.08.02" will be changed to "2015/08/02"

Separator is always hard coded.

Thanks,
 Zsaga

### CODE REVIEW

**Comment by blzaugg** [comment]
@zsagia, @peterborkut,

Yes the separators need to be localized. Do we have existing methods for this? I'm not familiar with what's available on the Java side.

@zsagia Please add replication steps for this on the ticket.

@peterborkuti,

I'm finding inconsistencies with the date formatting when the page loads vs after manipulation.

On Load en: `1/1/1970`
On Focus en: `01/01/1970`
hu and de seem fine.

We need to keep the leading zeros.

**Comment by peterborkuti** [comment]
Hi Byran,
@zsagia 

I am not 100% sure, that we should keep the leading zeros. I think, this depends on the localization.
If a locale formats a date without leading zeros, in my opinion, we should use this date-format on the javascript side also. So I think, that the format is better when page loads than after focusing and javascript breaks it.

What do you think about it, where should I fix it? On java side (which in my opinion breaks a bit localization) or javascript side? Fixing it from java is very easy.

**Comment by blzaugg** [comment]
For now, lets keep the leading zeros, for consistency/historical (UI) reasons.

If you'd like to create a ticket, that addresses non-leading zeros, with examples of locales which use it, that's fine. But in order to get this ticket completed faster, I'd like to minimize the scope of the changes.

**Comment by peterborkuti** [comment]
OK, thanks, I will do this when I get back from my holiday.

@zsagia

**Pull request closed without merging**
