### PR TITLE
LPS-95489 Apply getDocumentPosition on editorElement.getLast() instea…

### PR DESCRIPTION
**Pull request by gregory-bretall**
…d of editorElement

Looking for your thoughts on this, as far as I can tell it's not reproducible in master but should still theoretically apply.

Resent from https://github.com/gregory-bretall/liferay-portal/pull/196

https://issues.liferay.com/browse/LPS-95489

### CODE REVIEW

**Comment by gregory-bretall** [comment]
ci:test:sf

**Comment by gregory-bretall** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
I found an issue i will resend it,

**Comment by rolandpakai** [comment]
ci:close

**Pull request closed without merging**
