### PR TITLE
LPS-56240

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by bejondshao** [comment]
Hey @blzaugg, 

Would you take some time to review this? This ticket is urgent.

Thanks
Bejond

**Comment by blzaugg** [comment]
I plan to look at it today. It's next on my list.

**Comment by bejondshao** [comment]
Hey @blzaugg ?

**Comment by blzaugg** [comment]
Reviewing this morning. My other tickets took longer than expected.

**Comment by blzaugg** [comment]
https://github.com/natecavanaugh/liferay-portal/pull/3299

**Pull request closed without merging**
