### PR TITLE
Lps 94904

### PR DESCRIPTION
**Pull request by gregory-bretall**
https://issues.liferay.com/browse/LPS-94904

Change suggested by Julien Castelain here https://github.com/julien/liferay-portal/commit/9198a04327c7539c8638614a56530976d0a312c2

### CODE REVIEW

**Comment by gregory-bretall** [comment]
ci:test:sf

**Comment by gregory-bretall** [comment]
ci:test:relevant

**Comment by blzaugg** [comment]
I plan to review this tomorrow.

**Comment by blzaugg** [comment]
Pull request submitted at: https://github.com/jonmak08/liferay-portal/pull/2085
View total diff: https://github.com/blzaugg/liferay-portal/compare/c2e627f0ea...fc21dbce2f

**Pull request closed without merging**
