### PR TITLE
LPS-86526 Added top and bottom padding for center aligned images in b…

### PR DESCRIPTION
**Pull request by gregory-bretall**
…logs

https://issues.liferay.com/browse/LPS-86526

Resent from https://github.com/gregory-bretall/liferay-portal/pull/118

Test Results: https://github.com/gregory-bretall/liferay-portal/pull/118#issuecomment-431514512
https://github.com/gregory-bretall/liferay-portal/pull/118#issuecomment-431496279

@frankfu926

### CODE REVIEW

**Comment by blzaugg** [comment]
@frankfu926,

1) I hate these fixes. They smell horrible. Not our fault/choice, so I'll ignore that. No worries.

2) This looks incredibly fragile. This will break with a simple property order change. For example, if `margin-right: auto` comes before `margin-left: auto;`.

I'd rather see something like:
```
&[style*="display: block;"][style*="margin-left: auto;][style*="margin-right: auto;"],
&[style*="display:block;][style*="margin-left:auto;][style*="margin-right:auto;"],
```

This way, order is irrelevant.

Try this, to ensure it still accomplishes what you want then send it back.

**Comment by frankfu926** [comment]
@blzaugg 
1. Yeah... Sad... :disappointed: 
2. Thanks for pointing this out!! I didn't know we can group the different styles together in this way that makes the property order irrelevant. I will modify my changes, make sure they work, and send you an updated pull ASAP! :smiley:

**Comment by blzaugg** [comment]
thanks

**Comment by frankfu926** [comment]
New pull: https://github.com/blzaugg/liferay-portal/pull/191

**Pull request closed without merging**
