### PR TITLE
LPS-94945 Remove required validator from template

### PR DESCRIPTION
**Pull request by gregory-bretall**
Test Results: https://github.com/gregory-bretall/liferay-portal/pull/192#issuecomment-488105159
https://github.com/gregory-bretall/liferay-portal/pull/192#issuecomment-488326979

https://issues.liferay.com/browse/LPS-94945

### CODE REVIEW

**Comment by blzaugg** [comment]
Pull request submitted at: https://github.com/jonmak08/liferay-portal/pull/2070
View total diff: https://github.com/blzaugg/liferay-portal/compare/7171891f96...dc615bcde1

**Comment by blzaugg** [comment]
@fortunatomaldonado,

I found at least 2 other places that would have the same issue--a hidden field that's required.

```diff
diff --git a/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/resources/com/liferay/dynamic/
data/mapping/dependencies/ddm/color.ftl b/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/r
esources/com/liferay/dynamic/data/mapping/dependencies/ddm/color.ftl
index 3ada4e8..079a77e 100644
--- a/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/resources/com/liferay/dynamic/data/ma
pping/dependencies/ddm/color.ftl
+++ b/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/resources/com/liferay/dynamic/data/ma
pping/dependencies/ddm/color.ftl
@@ -26,10 +26,6 @@
                        name=namespacedFieldName
                        type="hidden"
                        value=fieldRawValue
-               >
-                       <#if required>
-                               <@liferay_aui.validator name="required" />
-                       </#if>
-               </@>
+               />
        </div>
 </@>
\ No newline at end of file
diff --git a/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/resources/com/liferay/dynamic/
data/mapping/dependencies/ddm/documentlibrary.ftl b/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/
src/main/resources/com/liferay/dynamic/data/mapping/dependencies/ddm/documentlibrary.ftl
index 9cf4312..1b7f76c 100644
--- a/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/resources/com/liferay/dynamic/data/ma
pping/dependencies/ddm/documentlibrary.ftl
+++ b/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/resources/com/liferay/dynamic/data/ma
pping/dependencies/ddm/documentlibrary.ftl
@@ -48,11 +48,7 @@
                        name=namespacedFieldName
                        type="hidden"
                        value=fieldRawValue
-               >
-                       <#if required>
-                               <@liferay_aui.validator name="required" />
-                       </#if>
-               </@>
+               />

                <div class="button-holder">
                        <@liferay_aui.button
```

Basically, any input of `type="hidden"` should not have a `<@liferay_aui.validator name="required" />` nor a `required=` attribute.

Please search of similar patterns and correct them as well.

**Comment by fortunatomaldonado** [comment]
Hello @blzaugg,

After removing the validator from the other templates, I found that the error message would no longer appear after trying to submit. This is due to `image.ftl` having another `aui.input` with `required`. This is needed due to how the template looks and the other templates do not have this or is needed. I believe we should leave this as is. Let me know what you think.
```
		<@liferay_aui.input
			helpMessage=escape(fieldStructure.tip)
			inlineField=true
			label=escape(label)
			name="${namespacedFieldName}Title"
			readonly="readonly"
			required=required
			type="text"
			value=(name?has_content)?string(name, languageUtil.get(locale, "drag-file-here"))
		/>
```

**Comment by blzaugg** [comment]
Let's chat tomorrow morning.

**Comment by fortunatomaldonado** [comment]
Resent https://github.com/blzaugg/liferay-portal/pull/218

**Pull request closed without merging**
