### PR TITLE
LPS-56739 Setting the Start parameter in Numbered List Properties does not work

### PR DESCRIPTION
**Pull request by zxdgoal**
Hey Byran

I am not quit sure if we should fix this because in ckeditor demo, it disables the function of setting start parameter for numbered list.

Should we follow this decision?

Anyway, I have developed a fix for this issue.

I have to extend list tag to allowing passing two parameters.

It used to be like this:
```
[list=1]
[*]123
[*]456
[*]789
[/list]
```
``1`` represents list style.

Now it becomes something like this:
```
[list=1,5]
[*]123
[*]456
[*]789
[/list]
```
``5`` represents list start.

Not quit sure if this is the best solution for this issue.

Please help reviewing 

Many thanks
John

### CODE REVIEW

**Comment by zxdgoal** [comment]
This fix breaks, do not use it.

Could you answer my question 
>I am not quit sure if we should fix this because in ckeditor demo, it disables the function of setting start parameter for numbered list. Should we follow this decision?

**Comment by blzaugg** [comment]
Yes and no.

For our BBCode syntax, this is a feature request, not a bug. There is no true "standard" to BBCode, and we've only implement a subset of syntax features other implementations may use.

But, as it looks like users are able to use this feature from the UI, I'd say we should have either supported the syntax or disable the UI. Same goes for the list types we just added in the last weeks. 

Also note, we'd still need the Java portion for this.

@ipeychev, any thoughts?

**Comment by ipeychev** [comment]
There is no much to add here, maybe these:
1. This is not a bug.
2. We really don't care what CKEditor does with BBCode and how do they handle it.
3. I would say it won't hurt if we add this to both of our BBCode parsers (server side and client side). I just don't feel very comfortable with adding more features to this component, considering the lack of UI unit tests in Portal. Was it requested by a customer or it was our idea to implement it?

Thanks,

**Comment by zxdgoal** [comment]
It is a customer issue.

**Comment by ipeychev** [comment]
Well, okay then... but we will have to fix it in both parsers. At least for the Java we should be able to write a test.

**Comment by zxdgoal** [comment]
Namely BBCodeParser.java?

**Comment by ipeychev** [comment]
The server-side parser code is very similar to the client side one. It is [here](https://github.com/liferay/liferay-portal/tree/c28c8f3573789f8ad777b55409eece414f220404/modules/portal/portal-parser-bbcode/src/com/liferay/portal/parser/bbcode).

**Comment by zxdgoal** [comment]
One thing I am not very comfortable is the syntax for handling the start of ``ol``.

Do you think it is ok to do this ?
```
[list=1,5]
[*]123
[*]456
[*]789
[/list]
```
or you have a better idea?

**Comment by blzaugg** [comment]
Are we making up our own BBCode syntax or did this come from some other BBCode implementation?

**Comment by zxdgoal** [comment]
This is our own BBCode syntax.

**Comment by blzaugg** [comment]
I cannot find any similar syntax examples. The only thing I find are single attribute values.
```
[tagname=attributevalue]
```
Are we sure we want to do it this way?

**Comment by zxdgoal** [comment]
I have no idea how to solve this problem if we decide to follow single attribute.

**Comment by blzaugg** [comment]
@ipeychev, do we want to extend attributes this far?

**Comment by zxdgoal** [comment]
If we cut off this function, e.g. setting start number for list, it is still acceptable to this customer.

**Comment by blzaugg** [comment]
We could, if numeric, use the number to start the list with, and if we find a single alpha character, use that letter to start the list with.

**Comment by blzaugg** [comment]
> If we cut off this function, e.g. setting start number for list, it is still acceptable to this customer.

I don't understand.

**Comment by zxdgoal** [comment]
For alpha character, we can still set start number.

For example, starting form 4, it will be 

D.XXX
E.XXX
F.XXX

**Comment by zxdgoal** [comment]
>I don't understand.

I meant we can disable the end user setting start for list from UI.

**Comment by blzaugg** [comment]
Ah.

**Comment by blzaugg** [comment]
One catch, with disabling it, we should only disable it for BBCode (Creole too?), and not HTML. So this would need to be a setting that is turned on in the BBCode Plugin when it's loaded.

**Comment by zxdgoal** [comment]
I think so.

For HTML editor, it works fine in ckeditor.com/demo#full as there is no technical challenge.

There should be a config for ckeditor to turn off this function.

**Comment by blzaugg** [comment]
Like so:
https://github.com/liferay/liferay-portal-ee/blob/ee-6.2.x/portal-web/docroot/html/js/editor/ckeditor_diffs/plugins/bbcode/plugin.js#L7-L9

**Comment by blzaugg** [comment]
We should have originally disable the `liststyle` plugin for BBCode and Creole. I assume we can't take them away now; right?

**Comment by zxdgoal** [comment]
I think we should add ``liststyle`` to [here](https://github.com/liferay/liferay-portal-ee/blob/ee-6.2.x/portal-web/docroot/html/js/editor/ckeditor_diffs/ckconfig_bbcode.jsp#L59-L77)

**Comment by blzaugg** [comment]
I like that idea. I'm just sure if we are allowed to at this point.

Maybe we shouldn't have added these tickets:
https://github.com/blzaugg/liferay-portal/commit/435f1c4549cdedbbd6211a547ecada463499008f
https://github.com/blzaugg/liferay-portal/commit/0a19c690c764307dd752630cfc2c60357ebf0ea1

@zsoltbalogh, could we disable a feature of CKEditor, we originally didn't support in our BBCode syntax but recently added?

**Comment by zxdgoal** [comment]
It seems there is no handy ckeditor config to disable the start from list style in UI.

We have to remove [this](https://github.com/liferay/liferay-ckeditor/blob/master/plugins/liststyle/dialogs/liststyle.js#L120-L151).

**Comment by zxdgoal** [comment]
The customer can only accept removing start option from dialog, not the whole style function.

**Comment by ipeychev** [comment]
Hey guys,

This syntax I don't like very much:
```
[list=1,5]
[*]123
[*]456
[*]789
[/list]
```

However, for image we already support [multiple attributes](https://github.com/liferay/liferay-portal/blob/c54360f634f86b687f46b43832911129e0cd8761/modules/frontend/frontend-editors-web/src/META-INF/resources/html/editors/ckeditor_diffs/plugins/bbcode/converter.js#L356).

This means we can update the way we store the attributes in the [list] start tag and instead to do "list=1,5" to add multiple attributes for "start" and list type and we will have something like:
```
[list start="5" type="1"]
```

Thoughts?

Thanks,

**Comment by zxdgoal** [comment]
@ipeychev 

Your syntax looks like that of HTML editor. I prefer yours to mine. :)

So, your vote is to fix this issue, rather than removing the start option from the list dialog in UI ?

**Comment by ipeychev** [comment]
Yes.

That won't be very hard and we won't invent custom BBCode syntax, so why not.

**Comment by zxdgoal** [comment]
OK, I will send a fix for your review.

**Comment by ipeychev** [comment]
Great. Please also update the way we fixed the other two tasks (435f1c4 and 0a19c69). Inside these [list] tags we will have not only one, but multiple attributes, just like for our [image] start tag. Also, these changes should be made to the server-side part of the BBCode parser/converter too.

**Comment by zxdgoal** [comment]
Understood.

**Comment by blzaugg** [comment]
A thought I just had. If we change the syntax for lists from `[list=1]` to `[list type="1"]`, won't this corrupt any existing content coming from the database? Isn't the content stored as BBCode or is it HTML in the database?

The need for this fix originates with ee-6.2.x.

Should we support both syntaxes? Reading both `[list=1]` and `[list type="1"]`, but only writing `[list type="1"]`to the database.

**Comment by ipeychev** [comment]
Byran, haven't we just introduced this? I had the impression that no one had created yet entries.
If not, then we have to do the following:
1. The BBCode parser should accept both syntaxes.
2. The converter from HTML to BBCode should use only the new one.

@blzaugg @zxdgoal

**Pull request closed without merging**
