### PR TITLE
[Technical Support] LPS-67718 Children nodes get selected automatically when click on "load more results"

### PR DESCRIPTION
**Pull request by zxdgoal**
Hey Byran

This is a fix for [LPS-67718](https://issues.liferay.com/browse/LPS-67718)

The issue is that when we select a parent page, and deselect some its children pages, after click on "load more results"(IO request), the deselected nodes are selected automatically.

The reason is that when IO completes, we will call ``_updateCheckedNodes``, which will force all chidlren node to be the same state with their parent node.

To solve this issue, updateCheckedNodes requires to be able to resolve two basic scenarios:

1. Explicit updateCheckedNodes. When click/unclick on a parent node, we expect all its children nodes to be selected/unselected automatically. In this case, we force all children node having consistent states with their parents.

2. Implict updateCheckedNodes. When click on load more results or detect childrenNodeChanges, we expect the all local changed children nodes remaining their current status and new loaded children nodes respect their original states. In this case, we allow children nodes and their parents having different states.

Let know if you have any concerns about the fix.

/cc @daledotshan @jonmak08

Thanks
John.

### CODE REVIEW

**Comment by blzaugg** [comment]
Forwarded to new SME: https://github.com/dustinryerson/liferay-portal/pull/74

**Comment by zxdgoal** [comment]
In the future, should I send UI pr to Dustin instead?

**Comment by jonmak08** [comment]
Hey @zxdgaol,

Yes, you can send all UI pull requet's to @dustinryerson as he is now the SME.

Please let me know if you have any questions. Thanks!

**Comment by zxdgoal** [comment]
Got it

**Pull request closed without merging**
