### PR TITLE
LPS-94945 Adjust required for templates

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-94945

Resending https://github.com/blzaugg/liferay-portal/pull/216
I updated the templates getting rid of the validations in the hidden fields. Let me know if there are any questions about this.
Thank you.

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Hello @blzaugg ,

We need an update on this ticket when you are available.

Sincerely,
Brian Kim

**Comment by blzaugg** [comment]
I should be able to wrap this up today.

**Comment by blzaugg** [comment]
https://github.com/fortunatomaldonado/liferay-portal/pull/4

**Pull request closed without merging**
