### PR TITLE
LPS-68581 Ignoring inline height to keep the ratio.

### PR DESCRIPTION
**Pull request by zxdgoal**
Hey Byran

As we discussed in forum, we can fix this issue on app level.

If in the future, we develope the feature in Alloy editor, then we can decide if we still need this fix.

But, currently, we need it in the respective of user-friendly.

Thanks
John.

/cc @jbalsas @juliocamarero @daledotshan

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @zxdgoal, @blzaugg, I have the feeling that this may happen across the board in other applications... could you please dig deeper to make sure we're not missing it in other places?

Thanks!

**Comment by zxdgoal** [comment]
Sure, could we get @natecavanaug's input on this issue? just wanna confirm it is in a right direction since we did reject the solution before.https://github.com/pat270/liferay-portal/pull/33

**Comment by blzaugg** [comment]
This is how we would have done it in 6.2:
https://github.com/blzaugg/liferay-portal-ee/blob/ee-6.2.x/portal-web/docroot/html/themes/classic/_diffs/css/custom_common.css#L858-L862

For master, it looks like this pattern isn't present.

It should probably be added to places like this:
- https://github.com/blzaugg/liferay-portal/blob/master/modules/apps/collaboration/wiki/wiki-web/src/main/resources/META-INF/resources/wiki/css/main.scss#L27-L29
- https://github.com/blzaugg/liferay-portal/blob/master/modules/apps/collaboration/blogs/blogs-web/src/main/resources/META-INF/resources/blogs/css/common_main.scss#L31-L33
- https://github.com/blzaugg/liferay-portal/blob/master/modules/apps/collaboration/blogs/blogs-web/src/main/resources/META-INF/resources/blogs/css/common_main.scss#L56-L58
- https://github.com/blzaugg/liferay-portal/blob/master/modules/apps/collaboration/message-boards/message-boards-web/src/main/resources/META-INF/resources/message_boards/css/main.scss#L98-L100
- https://github.com/blzaugg/liferay-portal/blob/master/modules/apps/collaboration/wiki/wiki-web/src/main/resources/META-INF/resources/wiki/css/main.scss#L27-L29

**Comment by blzaugg** [comment]
I think Patrick rejected https://github.com/pat270/liferay-portal/pull/33 is because of the `!important`, as well as the idea that we would fix it in CKEditor instead.

Since we are acknowledging this is a hack around the inline styles that Alloy adds, with the hopes of a future feature to allow for individual dimensions, I think your approach is fine.

**Comment by jbalsas** [comment]
Hey @blzaugg, I wouldn't say this is a hack around Alloy. All those portlets are adding specific code to handle how images appear. They should do so in a responsible and robust manner. 

Again, no feature in a specific editor can fix this, since there are many ways users can create content for these apps (including editing source code).

**Comment by blzaugg** [comment]
Hack is the wrong word. Circumvent.

**Comment by jbalsas** [comment]
Hey @blzaugg, I'm not trying to beat you at english vocabulary...

I'm trying to get you to understand that this is an issue in the portlets themselves. It may be more evident because of what the editor does, but by no means is there anyone else to blame here than the portlet. An image with fixed `width` and `height` is perfectly valid html and might even serve a specific purpose. Assuming this is not true and that our portlet can decide for the user will take us to an endless stream of insufficient bug fixes.

Even if we do implement your suggested feature in AlloyEditor (which we will), that won't fix this issue. I can think of at least 3 or 4 other ways to reproduce it. This needs to be fixed at the app level first. Then, we can move to whatever other feature we want to implement to help alleviate this.

Thanks.

**Comment by blzaugg** [comment]
I see your point that, "but by no means is there anyone else to blame here than the portlet". The Portlet has already made a decision for the user to set `max-width: 100%`, which causes this issue. But, it makes sense to me that, if we want to keep that decision in place, we'd best mitigate the side effects, revealed by static dimensions.

If we are unwilling to make default styling decisions for the user; why keep `max-width: 100%` at all?

For the typical (novice) user, I feel it's reasonable to set some styling defaults, like `max-width: 100%`, paired with `height: auto`, to free these users from worrying about the intricacies of responsive design.

For the atypical (advanced) user, they still have the ability to override the defaults the Portlet has set. Yes, they may have to use `!important`, in an inline style, to do that.

**Comment by jbalsas** [comment]
Yes, we're already working on your suggestion for the mitigation aspect of it.

**Pull request closed without merging**
