### PR TITLE
LPS-55079 The height of the code style in ckeditor is initialized too short.

### PR DESCRIPTION
**Pull request by zxdgoal**
Hey Byran

This is another solution for LPS-55079.

The original solution works, but has a side effect on IE.

For more details, see LPP-17064.

I simply tested this fix, and it looks fine. But could you test it a bit more?

I am a bit busy. I will try to help Ckeditor team about https://github.com/blzaugg/liferay-ckeditor/pull/4 and 
http://dev.ckeditor.com/ticket/13404 when I have time.

Thanks
John.

### CODE REVIEW

**Comment by zxdgoal** [comment]
I am not that comfortable with this fix.

**Comment by blzaugg** [comment]
Reopen LPS-55079, revert the original fix and resend this fix (or one you're more comfortable with).

I think we need to address these issues (LPS-55079, LPP-17064) together in one complete fix.

**Comment by zxdgoal** [comment]
/**
 * Disables the ability to resize objects (images and tables) in the editing area.
 *
 *		config.disableObjectResizing = true;
 *
 * **Note:** Because of incomplete implementation of editing features in browsers
 * this option does not work for inline editors (see ticket [#10197](http://dev.ckeditor.com/ticket/10197)),
 * does not work in Internet Explorer 11+ (see [#9317](http://dev.ckeditor.com/ticket/9317#comment:16) and
 * [IE11+ issue](https://connect.microsoft.com/IE/feedback/details/742593/please-respect-execcommand-enableobjectresizing-in-contenteditable-elements)).
 * In Internet Explorer 8-10 this option only blocks resizing, but it is unable to hide the resize handles.
 *
 * @cfg
 * @member CKEDITOR.config
 */
CKEDITOR.config.disableObjectResizing = false;

**Comment by zxdgoal** [comment]
Hey Byran

Could you have a look at above description for ``disableObjectResizing`` ?

It seems that this is a known issue for ckeditor for IEs.

I believe in ckeditor, it has its own way to handle IE resize handles.

**Comment by zxdgoal** [comment]
I have a fix for ee-6.2.x anyway https://github.com/blzaugg/liferay-portal-ee/pull/50

**Pull request closed without merging**
