### PR TITLE
 LPS-89633 Cannot reject or approve workflow task in IE11

### PR DESCRIPTION
**Pull request by noemi-zamarripa**
https://issues.liferay.com/browse/LPS-89633

Issue:
Approve and Reject options not working for Workflows in IE11.

Solution:
Added polyfill to support underlying function in IE11 and allow user to Approve/Reject workflow tasks.

### CODE REVIEW

**Comment by noemi-zamarripa** [comment]
ci:test:sf

**Comment by noemi-zamarripa** [comment]
ci:test:relevant

**Comment by blzaugg** [comment]
@noemi-zamarripa, how did you build/deploy `frontend-compatibility-ie`. it doesn't seem like the polyfill's JS is being processed properly.

When I run `gradle deploy` and test in IE, this gets delivered to the browser:
```js
import endsWith from './endsWith';

if (!String.prototype.endsWith) {
    String.prototype.endsWith = endsWith;
}
```

/cc @jonmak08. Any ideas?

**Comment by noemi-zamarripa** [comment]
@blzaugg I don't recall doing anything special to get it to deploy. I was initially having some issues building in master but those were due to my repo not being up to date and different gradle errors.

**Comment by blzaugg** [comment]
Figured it out. The polyfill is an ES6 module for some reason. I'll find another.

**Comment by noemi-zamarripa** [comment]
Gotcha 👍

**Comment by blzaugg** [comment]
Note, these changes cannot be tested on master HEAD, as there's a blocking bug.
https://github.com/jonmak08/liferay-portal/pull/2037

**Pull request closed without merging**
