### PR TITLE
LPS-66646 Same role can be selected multiple time while editing any user.

### PR DESCRIPTION
**Pull request by zxdgoal**
Hey Byran

This is a regression bug caused by LPS-52381. Please refer to it to keep updated.

When pop up an iframe to allow end user to select options, we actually have two scenarios(LPS-52381&LPS-66646).

1. Single select: That is we only allow end user to select only one option. This means every time when end user chose an option, we need to refresh all the options to be enabled except the option selected previously so that they can be selected again.

2. Mutli-select: That is we do allow end user to select more than one option. This means we never refresh options to be enabled and they are disabled as long as they are selected unless they are removed from the selection list explicitly.

By default. when calling ``selectEntityHandler`` without specifying ``disabled`` and ``singleSelect``, they are both ``true``.

So when multi select is allowed, we need to set them as ``true, false`` respectively.

Thanks
John

### CODE REVIEW

**Comment by zxdgoal** [comment]
ci:retest

**Comment by zxdgoal** [comment]
Does this fix break tests?

**Comment by zxdgoal** [comment]
It seems not breaking 6.2.x https://github.com/zxdgoal/liferay-portal-ee/pull/2

**Comment by zxdgoal** [comment]
I rebaseed and trigger ci test again but still failed. 

So, maybe the test fail is not caused by the fix.

**Comment by blzaugg** [comment]
https://github.com/jonmak08/liferay-portal/pull/1592

**Pull request closed without merging**
