### PR TITLE
[TECHNICAL REQUEST] LPS-59732 Change in the Look&Feel in a portlet of a Page Template will blank out JavaScript and Query String field of a page created from that template

### PR DESCRIPTION
**Pull request by zsagia**
Hi Byran,

I made this fix based on Eduardo's but I modified it a bit. I used a new css class('propagatable-field') to collect easily those fields which we will want to disable/enable instead of using disable attribute.
Furthermore I added theme's inputs to these fields because a page-template propagation modified that as well.

Please review it.

Thanks,
 Zsaga

### CODE REVIEW

**Comment by blzaugg** [comment]
What's the difference between: 
`selLayout.isLayoutPrototypeLinkEnabled()` 
and 
`selLayout.isLayoutPrototypeLinkActive()`

**Comment by blzaugg** [comment]
Reading the "docs" didn't help me:
https://github.com/blzaugg/liferay-portal/blob/7df2caf/portal-service/src/com/liferay/portal/model/LayoutWrapper.java#L1478-L1498

*isLayoutPrototypeLinkActive()*
> Returns <code>true</code> if the current layout is built from a layout template and still maintains an active connection to it.

*isLayoutPrototypeLinkEnabled()*
> Returns <code>true</code> if this layout is layout prototype link enabled.

What is "layout prototype link enabled"?

**Comment by blzaugg** [comment]
bump

**Comment by zsagia** [comment]
Hi Byran,

I just tried to follow those patterns which I found in details.jsp.

I can send you another pull with those changes which you wanted.

Thanks,
 Zsaga

**Comment by blzaugg** [comment]
I'd like @epgarcia to review your new PR first, to ensure you're both expecting/accept the same behavior.

Also, I don't have confidence in my understanding of `isLayoutPrototypeLinkActive` vs `isLayoutPrototypeLinkEnabled`, to determine which is appropriate to use.

@epgarcia, please send me the PR after you review it.

**Pull request closed without merging**
