### PR TITLE
LPS-54493

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Not quite sure about this fix. See https://github.com/hhuijser/liferay-portal/pull/2325

**Comment by zxdgoal** [comment]
Bump

**Comment by blzaugg** [comment]
Sorry, I was working on an escalation. I'll review this, this morning.

**Comment by zxdgoal** [comment]
I like your solution.

I did expect something like version ID appending with the upload.js to bust browser caching it.

Could you lead me how we do that in Liferay?

Thanks
John

**Comment by blzaugg** [comment]
I don't know how it's normally done. @jonmak08, do you know?

**Comment by zxdgoal** [comment]
I believe adding ``com.liferay.portal.servlet.filters.language.LanguageFilter=false`` could be a possible solution for the customer.

**Comment by blzaugg** [comment]
There would be a performance impact (not sure how much) to the site if you did this. Every language key in JS would be a unique AJAX request.

For this `upload.js` file, it would be an additional 26 requests when the uploader was displayed.

**Comment by zxdgoal** [comment]
Hey @blzaugg 

To what extent, you consider this issue as a bug?

For me, it is not that obvious.

**Comment by natecavanaugh** [comment]
> Hey @blzaugg
> To what extent, you consider this issue as a bug?
> For me, it is not that obvious.

Having the Liferay.Language.get method run 26 times would be terrible. It's not just that there are 26 additional requests, but that each request is a blocking request meaning that each one has to wait until the previous one is done. On a slow connection, or a network with a high latency, this could be quite a lot of time, for every single page load.
Even worse, a lot of browsers, such as IE, will completely freeze the entire browser until the requests have come back.
Imagine your browser just hanging for a few minutes if your wifi signal is bad, or your provider is experiencing high traffic.

Just to let you know why disabling the language filter is *NOT* recommended :)

**Comment by zxdgoal** [comment]
Fair enough.

Thanks for your explanation, @natecavanaugh 

Any ideas about how to append language Id to js name?

I believe Byran's suggestion is good enough as a solution.

Thanks
John

**Comment by blzaugg** [comment]
I've seen it done in `ckeditor.jsp`. I just don't know what query string parameters are normal.

https://github.com/liferay/liferay-portal/blob/master/portal-web/docroot/html/js/editor/ckeditor.jsp#L466

But, just adding `languageId`, should get you the result you want.

**Comment by natecavanaugh** [comment]
Part of the issue is that the YUI Loader doesn't add the language key to the url, so here's a possible solution: https://github.com/natecavanaugh/liferay-portal/commit/a30e3c0dcd4d413752893c0672849d685aed941c
But we would also need to add the language key to each JS file as we loop through them [here](https://github.com/natecavanaugh/liferay-portal/blob/LPS-54493/portal-web/docroot/html/common/themes/top_portlet_resources_js.jspf) and [here](https://github.com/natecavanaugh/liferay-portal/blob/LPS-54493/portal-web/docroot/html/common/themes/bottom_portlet_resources_js.jspf) (there might be some other places as well).

**Comment by zxdgoal** [comment]
Hey @blzaugg 

Could you take charge of LPS-54493 for me ?

I am a bit overflowed.  

I will appreciate it a lot

BTW, the related LPP is due. 

Please give it priority. 

Thanks
John.

**Comment by blzaugg** [comment]
@zxdgoal, yes I can. Please assign the ticket to me, using the normal escalation process.

**Pull request closed without merging**
