### PR TITLE
LPS-55921

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by zxdgoal** [comment]
@blzaugg

**Comment by blzaugg** [comment]
I'll be able to look at this tomorrow.

**Comment by zxdgoal** [comment]
Cool. Thx

**Comment by zxdgoal** [comment]
Hey Byran

I assume you have no time to review this pr.

Can I pass it to Jon?

Thanks
John.

**Comment by blzaugg** [comment]
Sorry, I pushed this to Jon last night. We may have some issues with it though. I'll talk to Jon.

https://github.com/jonmak08/liferay-portal/pull/1261

**Pull request closed without merging**
