### PR TITLE
LPS-71856 SF

### PR DESCRIPTION
**Pull request by Robert-Frampton**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey guys, sorry to sneak up on this, but changing this feature completely is not the right fix.

The solution mightbe hacky because CKEditor doesn't provide the proper APIs, but it fullfills
the UX andaccessibility requirements that were
given. We need to find a way to maintain that.

**Comment by dustinryerson** [comment]
@jbalsas no worries at all, thank you very much for your input!

**Comment by NolanChan** [comment]
Hi @jbalsas , thank you for the response. May I ask what the exact UX and accessibility requirements are? It seems from LPS-44056 that the only UX/Accessibility requirements are that "we need a way to let users know about [the help shortcut]." The provided solution in the LPS was to display a button next to the 'help' text with 'Alt+0'. My fix does exactly this. 

Please let me know if I'm missing something.

**Comment by jbalsas** [comment]
Hey @NolanChan, sure!

As you may guess, `LPS-44056` didn't collect those requirements. When facing an existing solution and missing or contradicting documentation, assume that the solution was done for a reason and it should likely be preserved.

In this case, after discussing it with our UX department, they wanted something outside of the regular button toolbars, with a slightly different styling (more of a tooltip than a button) that would be seen as a notice rather than as an action button. 

So, even though your fix does exactly what the LPS said we needed, there was more to it and the existing implementation should hint at that. On top of that, big UI changes like this aren't usually candidates to be backported.

Could you please work on this issue while keeping the existing behaviour?

**Pull request closed without merging**
